services:
  db:
    image: postgres:latest
    container_name: mydrive-postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - mydrive_backend
    volumes:
      - mydrive_postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  mydrive_postgres_data:

networks:
  mydrive_backend:
    driver: bridge
